# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qa.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from main import main
import sys
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.para_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.para_textEdit.setGeometry(QtCore.QRect(20, 150, 331, 341))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.para_textEdit.setFont(font)
        self.para_textEdit.setObjectName("para_textEdit")
        self.para_textEdit.setStyleSheet("background-color: white;border: 1px solid black")

        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(20, 30, 491, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title.setFont(font)
        self.title.setObjectName("title")

        self.para_label = QtWidgets.QLabel(self.centralwidget)
        self.para_label.setGeometry(QtCore.QRect(20, 120, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.para_label.setFont(font)
        self.para_label.setObjectName("para_label")

        self.qn_label = QtWidgets.QLabel(self.centralwidget)
        self.qn_label.setGeometry(QtCore.QRect(380, 120, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.qn_label.setFont(font)
        self.qn_label.setObjectName("qn_label")

        self.ans_label = QtWidgets.QLabel(self.centralwidget)
        self.ans_label.setGeometry(QtCore.QRect(380, 220, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ans_label.setFont(font)
        self.ans_label.setObjectName("ans_label")

        self.ans_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.ans_label_2.setGeometry(QtCore.QRect(380, 260, 391, 61))
        self.ans_label_2.setStyleSheet("background-color: white;border: 1px solid black")
        self.ans_label_2.setText("")
        self.ans_label_2.setObjectName("ans_label_2")

        self.qn_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.qn_textEdit.setGeometry(QtCore.QRect(380, 150, 391, 51))
        self.qn_textEdit.setObjectName("qn_textEdit")
        self.qn_textEdit.setStyleSheet("background-color: white;border: 1px solid black")

        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(380, 415, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.result_label.setFont(font)
        self.result_label.setObjectName("result_label")
        self.result_label.setWordWrap(True)
        self.result_label.setAlignment(Qt.AlignCenter)
        self.result_label.setText('Please enter your paragraph and your question to begin!')

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 350, 121, 41))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.on_click)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def on_click(self):
        self.result_label.setText('Processing..')
        self.result_label.repaint()
        res = main(self.para_textEdit.toPlainText(), self.qn_textEdit.toPlainText())
        self.ans_label_2.setText(res)
        self.result_label.setText('Here is your answer!')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Question Answering Tool"))
        self.title.setText(_translate("MainWindow", "Question Answering Tool with BERT!"))
        self.para_label.setText(_translate("MainWindow", "Paragraph"))
        self.qn_label.setText(_translate("MainWindow", "Question"))
        self.ans_label.setText(_translate("MainWindow", "Answer"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
